# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 1
        resnet: 1
        object detection: 3
        segmentation: 3
        anomaly detection: 1

# 通知の閾値
score_threshold: 0
