# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        category1:
                SLACK_ID: SLACK_ID1
                key:
                        segmentation: 3
                        anomaly detection: 1
        category2:
                SLACK_ID: SLACK_ID2
                key:
                        kaggle: 1
                        resnet: 1


# 通知の閾値
score_threshold: 0
