name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '00 3 * * *'
  workflow_dispatch:
  
  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2

      - name: install dependencies
        run: poetry install

      - name: Run owl
        run:
          poetry run python src/carrier_owl.py
        env:
          SLACK_ID1: ${{ secrets.SLACK_ID1 }}
          SLACK_ID2: ${{ secrets.SLACK_ID2 }}
          LINE_TOKEN1: ${{ secrets.LINE_TOKEN1 }}
          LINE_TOKEN2: ${{ secrets.LINE_TOKEN2 }}
          SECRETS: ${{ secrets }}


